version: '3.4'

services:
  vincia.api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vincia-api
    restart: always
    dns:
      - 8.8.8.8
    environment:
      APP_SECRET_KEY: 
      API_ENVIRONMENT: 
      AUTH0_DOMAIN: 
      AUDIENCE: 
      CONNECTION_STRING_DB: 
      OPENAI_KEY: 
    ports:
      - 8080:8080