version: '3.4'

services:
  vincia.api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vincia-api
    restart: always
    dns:
      - 8.8.8.8
    environment:

    ports:
      - 8080:8080